version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ikvolume:/ProgramsData/docker/volumes
volumes:
  ikvolume:
    driver: local
